baseURL = "https://ackersyndikat.org"
title = "Ackersyndikat"
DefaultContentLanguage = "de"
disableKinds = ["taxonomy","taxonomyTerm","sitemap","RSS"]
assetDir = "layout"
layoutDir = "layout"

[imaging]
quality = 60
resampleFilter = "lanczos"

[permalinks]
pages = "/:filename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
